export const LOAD_USER_DATA = "[USER] LOAD_USER_DATA";
export const LOAD_USER_DATA_SUCCESS = "[USER] LOAD_USER_DATA_SUCCESS";
export const LOAD_USER_SUBSCRIPTIONS = "[USER] LOAD_USER_SUBSCRIPTIONS";
export const LOAD_USER_SUBSCRIPTIONS_SUCCESS =
  "[USER] LOAD_USER_SUBSCRIPTIONS_SUCCESS";

export const LOAD_UPCOMING_LESSONS = "[USER] LOAD_UPCOMING_LESSONS";
export const LOAD_UPCOMING_LESSONS_SUCCESS =
  "[USER] LOAD_UPCOMING_LESSONS_SUCCESS";
export const LOAD_UPCOMING_LESSONS_FAILURE =
  "[USER] LOAD_UPCOMING_LESSONS_FAILURE";
export const LOAD_USER_SUBSCRIPTIONS_FAILURE =
  "[USER] LOAD_USER_SUBSCRIPTIONS_FAILURE";
