export const REGISTRATION = "[AUTH] REGISTRATION";
export const SEND_CODE_VERIFICATION = "[AUTH] SEND_CODE_VERIFICATION";
export const SEND_CODE_VERIFICATION_SUCCESS =
  "[AUTH] SEND_CODE_VERIFICATION_SUCCESS";

export const USER_VERIFIED = "[AUTH] USER_VERIFIED";

export const SIGN_OUT = "[AUTH] SIGN_OUT";
export const SIGN_OUT_SUCCESS = "[AUTH] SIGN_OUT_SUCCESS";
export const PHONE_VERIFIED = "[AUTH] PHONE_VERIFIED";
export const PHONE_VERIFICATION = "[AUTH] PHONE_VERIFICATION";

export const HANDLE_EXISTING_USER = "[AUTH] HANDLE_EXISTING_USER";
