export const LOAD_SERVICES = "[BOOKING] LOAD_SERVICES";
export const LOAD_COACHES_FOR_INDIVIDUAL_SERVICE =
  "[BOOKING] LOAD_COACHES_FOR_INDIVIDUAL_SERVICE";
export const LOAD_AVAILABLE_DATES_FOR_INDIVIDUAL_SERVICE =
  "[BOOKING] LOAD_AVAILABLE_DATES_FOR_INDIVIDUAL_SERVICE";
export const LOAD_AVAILABLE_DATES_FOR_INDIVIDUAL_SERVICE_SUCCESS =
  "[BOOKING] LOAD_AVAILABLE_DATES_FOR_INDIVIDUAL_SERVICE_SUCCESS";
export const LOAD_COACHES_FOR_INDIVIDUAL_SERVICE_SUCCESS =
  "[BOOKING] LOAD_COACHES_FOR_INDIVIDUAL_SERVICE_SUCCESS";
export const LOAD_SERVICES_SUCCESS = "[BOOKING] LOAD_SERVICES_SUCCESS";
export const LOAD_SELECTED_BOOKING = "[BOOKING] LOAD_SELECTED_BOOKING";
export const LOAD_SELECTED_BOOKING_SUCCESS =
  "[BOOKING] LOAD_SELECTED_BOOKING_SUCCESS";
export const LOAD_GROUP_EVENTS = "[BOOKING] LOAD_GROUP_EVENTS";
export const BOOK_GROUP_EVENT = "[BOOKING] BOOK_GROUP_EVENT";
export const BOOK_INDIVIDUAL_LESSON = "[BOOKING] BOOK_INDIVIDUAL_LESSON";
export const CANCEL_GROUP_EVENT = "[BOOKING] CANCEL_GROUP_EVENT";
export const CANCEL_GROUP_EVENT_SUCCESS =
  "[BOOKING] CANCEL_GROUP_EVENT_SUCCESS";
export const BOOK_GROUP_EVENT_SUCCESS = "[BOOKING] BOOK_GROUP_EVENT_SUCCESS";
export const BOOK_GROUP_EVENT_FAILURE = "[BOOKING] BOOK_GROUP_EVENT_FAILURE";
export const LOAD_GROUP_EVENTS_SUCCESS = "[BOOKING] LOAD_GROUP_EVENTS_SUCCESS";
